#!/usr/bin/bash

pyfile=$PYFILE
output_file="${pyfile%.py}.pyc"

echo "Compiling $pyfile ..."
echo -e "#!/usr/bin/python3\n" | cat - "$pyfile" | \
	     python3 -m compileall -b "$pyfile" > /dev/null 2>&1
